; PlatformIO Project Configuration File
; Automated conversion for spektrometr_esp32

[platformio]
src_dir = .
default_envs = spektrometr_esp32

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    Wire
    SPI

[env:spektrometr_esp32]
build_src_filter = +<spektrometr_esp32/> -<*>
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit AS7341
    bodmer/TFT_eSPI
